const PRIMARY_PURPLE = "#5f2eea";
const PRIMARY_BLUE = "#1d0071";
const DISABLE_PURPLE="#AA99DA";
const COMMON_WHITE = "#ffffff";
const COMMON_BLACK = "#000000";
const DISABLE_GREY="#C3CED9";
export { PRIMARY_PURPLE, PRIMARY_BLUE,DISABLE_PURPLE, COMMON_WHITE, COMMON_BLACK,DISABLE_GREY };
